name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo
        run: | 
          echo "hello"
          echo "hello2"
  build:
    needs: [build-docker-1]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
         - uses: actions/checkout@v4
         - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
           uses: actions/setup-dotnet@v3
           with:
            dotnet-version: ${{ matrix.dotnet-version }}
         - name: Install dependencies
           run: dotnet restore
         - name: Build
           run: dotnet build --configuration Release --no-restore
         - name: Test
           run: dotnet test --no-restore --verbosity normal */


  builddocker:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v4
           name: Check out code
         - name: Login to GitHub container registry
           run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
         - name: Build Docker image
           uses: docker/build-push-action@v3
           with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

       


