name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo
        run: | 
          echo "hello"
          echo "hello2"
  build:
    needs: [build-docker-1]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
         - uses: actions/checkout@v4
         - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
           uses: actions/setup-dotnet@v3
           with:
            dotnet-version: ${{ matrix.dotnet-version }}
         - name: Install dependencies
           run: dotnet restore
         - name: Build
           run: dotnet build --configuration Release --no-restore
         - name: Test
           run: dotnet test --no-restore --verbosity normal


  builddocker:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v4
           name: Check out code
         - uses: mr-smithers-excellent/docker-build-push@v6
           name: Build & push Docker image
           with:
             image: repo/image
             tags: v1, latest
             registry: registry-url.io
             dockerfile: Dockerfile.ci
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}


